events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # 关键：禁止 Nginx 把相对 Location 改写成 http://host:8080/...
  absolute_redirect off;
  port_in_redirect  off;

  include /etc/nginx/conf.d/*.conf;
}
